/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * Se elimina debido a que no estamos usando la FPU, de hecho se desactiva del proyecto
 * propiedades > c/c++ build > settings > MCU setting
 *
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/


/*
int main(void)
{
    // Loop forever
	// for(;;);

	*(uint32_t *)0x40023830UL |= (1 << 0);
	*(uint32_t *)0x40020000UL |= (1 << 10);

	while(1){

		*(uint32_t *)0x40020014UL |= (1 << 5);
		delay(300000);
		*(uint32_t *)0x40020014UL &= ~(1 << 5);
		delay(2000000);

	}
}
*/

#include <stdbool.h>
#include <stdint.h>
#include <stm32f446xx.h>
#include <stm32f446xx_gpio.h>

GPIO_handle_t LED;
GPIO_handle_t LED_2;
GPIO_handle_t BUTTON;

void delay(uint32_t cnt)
{
	while(cnt)
		cnt--;
}

void GPIO_LED_Init(void)
{
	LED.pGPIOx = GPIOA;
	LED.GPIO_config.GPIO_Mode = GPIO_Mode_OUT;
	LED.GPIO_config.GPIO_OType = GPIO_OType_PP;
	LED.GPIO_config.GPIO_Pin =	GPIO_PIN_6;
	LED.GPIO_config.GPIO_PuPd = GPIO_PuPd_NONE;
	LED.GPIO_config.GPIO_Speed = GPIO_Speed_LOW;

	GPIO_Init(&LED);

	LED_2.pGPIOx = GPIOA;
	LED_2.GPIO_config.GPIO_Mode = GPIO_Mode_OUT;
	LED_2.GPIO_config.GPIO_OType = GPIO_OType_PP;
	LED_2.GPIO_config.GPIO_Pin =	GPIO_PIN_5;
	LED_2.GPIO_config.GPIO_PuPd = GPIO_PuPd_NONE;
	LED_2.GPIO_config.GPIO_Speed = GPIO_Speed_LOW;

	GPIO_Init(&LED_2);

	BUTTON.pGPIOx = GPIOC;
	BUTTON.GPIO_config.GPIO_Mode = GPIO_Mode_IN;
	BUTTON.GPIO_config.GPIO_Pin =	GPIO_PIN_13;
	BUTTON.GPIO_config.GPIO_PuPd = GPIO_PuPd_NONE;
	BUTTON.GPIO_config.GPIO_Speed = GPIO_Speed_LOW;

	GPIO_Init(&BUTTON);
}


int main(void)
{
	GPIO_LED_Init();

	while(true){
		bool rest = true;

		GPIO_TogglePin(LED.pGPIOx, GPIO_PIN_6);
		GPIO_TogglePin(LED.pGPIOx, GPIO_PIN_5);
		delay(1500000);

		GPIO_TogglePin(LED.pGPIOx, GPIO_PIN_6);
		GPIO_TogglePin(LED.pGPIOx, GPIO_PIN_5);
		delay(500000);

		if(!GPIO_ReadPin(BUTTON.pGPIOx, GPIO_PIN_13)){
			while(rest){
				GPIO_TogglePin(LED.pGPIOx, GPIO_PIN_6);
				GPIO_TogglePin(LED.pGPIOx, GPIO_PIN_5);
				delay(80000);

				GPIO_WritePin(LED.pGPIOx, GPIO_PIN_6, RESET);
				GPIO_WritePin(LED.pGPIOx, GPIO_PIN_5, RESET);
				delay(80000);

				if(!GPIO_ReadPin(BUTTON.pGPIOx, GPIO_PIN_13))
					rest = true;
				else
					rest = false;
			}
		}
	}

	return 0;
}
